version: "3.8"

networks:
  rest-api:

services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    #env_file:
    #  - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=segmentation
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - rest-api

  app:
    container_name: app
    build: .
    volumes:
      - ./logs:/logs
      - ./secrets:/secrets
    #env_file:
    #  - .env
    environment:
      - HTTP_ADDR=:8080
      - LOG_LEVEL=debug
      - PG_URL=postgres://postgres:qwerty@postgres:5432/segmentation
      - CONFIG_PATH=/go/src/server/config/config.yml
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - rest-api

volumes:
  pg-data:
